name: rllab_goal_rl
channels:
    - https://conda.anaconda.org/kne
    - https://conda.binstar.org/tlatorre
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
    - soumith
dependencies:
    - python==3.5.2
    - numpy
    - scipy
    - path.py
    - python-dateutil
    - joblib
    - mako
    - ipywidgets
    - numba
    - flask
    - pybox2d
    - pygame
    - h5py
    - matplotlib
    - opencv3
    - scikit-learn
    - pytorch
    - torchvision
    - Cython
    - pip:
        - Pillow
        - atari-py
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - msgpack-python
        - Cython
        - cached_property
        - line_profiler
        - cloudpickle
        - redis
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - git+https://github.com/plotly/plotly.py.git@2594076e29584ede2d09f2aa40a8a195b3f3fc66#egg=plotly
        - awscli
        - git+https://github.com/openai/gym.git@385a85fd0c1b26ab1374f208fbb370e22647548d#egg=gym
        - pyglet
        - git+https://github.com/neocxi/prettytensor.git
        - jupyter
        - progressbar2
        - chainer==1.18.0
        - tensorflow-gpu; 'linux' in sys_platform
        - tensorflow; sys_platform == 'darwin'
        - dominate
        - scikit-image
        - git+https://github.com/tflearn/tflearn.git
